export const APPNAME = "TrustMarket";
export const LANG = "fr";
export const DESCRIPTION = "Achat en ligne facile, sécurisé";
export const URL = "https://trustmarket.store";
export const PHONE_NUM_AIRTEL = "+243 (0) 997 952 056";
export const PHONE_NUM_AFRICELL = "+243 (0) 905 416 308";
export const WA_NUM = "243997952056";
export const INFO_EMAIL = "info@trustmarket.store";
export const ADDRESS = "Goma, Bâtiment Equity BCDC";
